//
// Created by dzl on 13.04.16.
//

#ifndef PROJECT_TECHNOSPHERE_C_ERRORS_H
#define PROJECT_TECHNOSPHERE_C_ERRORS_H

enum errors_t {
    INCORRECT_STATUS,
    INCORRECT_PRIORITY,
    INCORRECT_REGULARITY,
    INCORRECT_COLOR
};

#endif //PROJECT_TECHNOSPHERE_C_ERRORS_H
